// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLf9t2g8OZAAGGGtcyuYxj1sNCkmsCG3A',
    appId: '1:271323359015:web:d95dcd3977f2a331052b02',
    messagingSenderId: '271323359015',
    projectId: 'careergpt-abbasi',
    authDomain: 'careergpt-abbasi.firebaseapp.com',
    storageBucket: 'careergpt-abbasi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Z5HhnzdG6Xolf7wBnY75a82nS2wH8co',
    appId: '1:271323359015:android:62c8b678b6a1b44e052b02',
    messagingSenderId: '271323359015',
    projectId: 'careergpt-abbasi',
    storageBucket: 'careergpt-abbasi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLf9t2g8OZAAGGGtcyuYxj1sNCkmsCG3A',
    appId: '1:271323359015:web:a3b5c75aa1eac005052b02',
    messagingSenderId: '271323359015',
    projectId: 'careergpt-abbasi',
    authDomain: 'careergpt-abbasi.firebaseapp.com',
    storageBucket: 'careergpt-abbasi.firebasestorage.app',
  );
}
